// <auto-generated />
using System;
using ContemporaryProgrammingFinal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContemporaryProgrammingFinal.Migrations
{
    [DbContext(typeof(BreakfastInfoContext))]
    partial class BreakfastModelsSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContemporaryProgrammingFinal.Models.Breakfast", b =>
            {
                b.Property<string>("Name")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("nvarchar(max)");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<string>("Name"));

                b.Property<DateTime>("Hot")
                    .HasColumnType("nvarchar(1)");

                b.Property<string>("Cold")
                    .HasColumnType("nvarchar(1)");

                b.Property<string>("Refridgerated")
                    .HasColumnType("nvarchar(1)");

                b.Property<int>("Calories")
                    .HasColumnType("int)");

                b.Property<int>("FatContent")
                    .HasColumnType("int");

                b.HasKey("Name");

                b.ToTable("Breakfast");

                b.HasData(
                    new
                    {
                        Name = "Eggs",
                        Hot = "y",
                        Cold = "n",
                        Refridgerated = "n",
                        Calories = 78,
                        FatContent = 5
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
